--- #YAML:1.0
name:               App-BackupPlan
version:            0.0.2
abstract:           Perl extension for automated, regular backups
author:
    - gualtiero chiaia <gchiaia@prismaqg.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Archive::Tar:   1.88
    File::Find:     1.15
    Log::Log4perl:  1.33
    XML::DOM:       1.44
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
